export enum QueuePayloadType {
	PROFILE_ANALYSIS = 'PROFILE_ANALYSIS',
	PROFILE_ANALYSIS_READY = 'PROFILE_ANALYSIS_READY',
	DOCUMENT_GENERATION = 'DOCUMENT_GENERATION',
	DOCUMENT_GENERATION_READY = 'DOCUMENT_GENERATION_READY',
}
