import { getHonoInstance } from '@/hono';
import { createRoute } from '@hono/zod-openapi';
import { z } from 'zod';
import {
    _401Describe,
    _404Describe,
    _500Describe,
    response2xxSchemaWrapper
} from '@/openapi';
import { OpenAPITags, APIErrorCodes } from '@/constants';
import { clerkEnforced, clerkValidate } from '@/middleware';
import { status } from '@poppanator/http-constants';
import { eq, and } from 'drizzle-orm';

const LessonSchema = z.object({
    id: z.string(),
    documentId: z.string(),
    title: z.string().nullable().optional(),
    content: z.string(),
    createdAt: z.number().optional()
});

export function setupGetLessonRoute() {
    const app = getHonoInstance();

    const spec = createRoute({
        method: 'get',
        path: '/documents/{documentId}/lesson',
        tags: [OpenAPITags.DOCUMENTS],
        operationId: 'getDocumentLesson',
        middleware: [clerkValidate, clerkEnforced],
        request: {
            params: z
                .object({
                    documentId: z.string()
                })
                .strict()
        },
        responses: {
            [status.Ok]: {
                description: 'Lesson retrieved successfully',
                content: {
                    'application/json': {
                        schema: response2xxSchemaWrapper(LessonSchema)
                    }
                }
            },
            [status.Unauthorized]: _401Describe,
            [status.NotFound]: _404Describe,
            [status.InternalServerError]: _500Describe
        }
    });

    app.openapi(spec, async (c) => {
        const { log, drizzleDB, dbTables } = c.env;
        const { docTable, quizQuestionTable } = dbTables;

        try {
            const documentId = c.req.param('documentId');
            const clerkId = c.get('clerkUserId');

            const existingDoc = await drizzleDB.query.docTable.findFirst({
                where: and(
                    eq(docTable.id, documentId),
                    eq(docTable.clerkId, clerkId)
                ),
                columns: { id: true, status: true }
            });

            if (!existingDoc) {
                return c.json(
                    {
                        code: 'document_not_found',
                        message: 'Document not found or unauthorized'
                    },
                    status.NotFound
                );
            }

            if (existingDoc.status !== 'READY') {
                return c.json(
                    {
                        code: 'lesson_not_ready',
                        message: 'The lesson is still being generated by the AI'
                    },
                    status.NotFound
                );
            }

            const lesson = await drizzleDB.query.quizQuestionTable.findFirst({
                where: eq(quizQuestionTable.documentId, documentId),
                columns: {
                    id: true,
                    documentId: true,
                    createdAt: true
                }
            });

            if (!lesson) {
                return c.json(
                    {
                        code: 'lesson_not_found',
                        message: 'No lesson content was found for this document'
                    },
                    status.NotFound
                );
            }

            return c.json(
                {
                    data: {
                        id: lesson.id,
                        documentId: lesson.documentId,
                        createdAt: lesson.createdAt
                            ? Number(lesson.createdAt)
                            : undefined
                    }
                },
                status.Ok
            );
        } catch (e: any) {
            log.withError(e).error(
                e.message || 'unknown error in lesson route'
            );

            return c.json(
                { message: 'unknown server error' },
                status.InternalServerError
            );
        }
    });
}
