import { sqliteTable as table } from 'drizzle-orm/sqlite-core';
import * as t from 'drizzle-orm/sqlite-core';
import { createdAtUpdatedAt } from '@/db/util';
import { relations } from 'drizzle-orm';

export const userTable = table('users', {
	clerkId: t.text('user_id').primaryKey(),
	...createdAtUpdatedAt()
});
export type DBUser = typeof userTable.$inferSelect;

export const profileTable = table('profiles', {
	id: t.text('profile_id').primaryKey(),
	clerkId: t
		.text('user_id')
		.notNull()
		.references(() => userTable.clerkId, {
			onUpdate: 'cascade',
			onDelete: 'cascade'
		}),
	name: t.text('name').notNull(),
	qna: t.text('qna').$type<{
		question: string,
		answer: string,
	}[]>().notNull(),
	status: t.text({
		enum: ['PENDING', 'READY']
	}).default('PENDING'),
	visualScore: t.integer('visual_score').default(-1), // value generated by AI
	auditoryScore: t.integer('auditory_score').default(-1), /// value generated by AI
	readingScore: t.integer('reading_score').default(-1), // value generated by AI
	kinestheticScore: t.integer('kinesthetic_score').default(-1), // value generated by AI
	...createdAtUpdatedAt()
});
export type DBProfiles = typeof profileTable.$inferSelect;

export const docTable = table('documents', {
	id: t.text('material_id').primaryKey(),
	clerkId: t
		.text('user_id')
		.notNull()
		.references(() => userTable.clerkId, {
			onUpdate: 'cascade',
			onDelete: 'cascade'
		}),
	profileId: t
		.text('profile_id')
		.notNull()
		.references(() => profileTable.id, {
			onUpdate: 'cascade',
			onDelete: 'cascade'
		}),
	status: t.text({
		enum: ['PENDING', 'READY']
	}).default('PENDING'),
	title: t.text('title'), // value generated by AI
	description: t.text('description'), // value generated by AI
	category: t.text('category').default('General'), // value generated by AI
	progressPercentage: t.real().default(-1),
	...createdAtUpdatedAt()
});
export type DBDocs = typeof docTable.$inferSelect;

export const fileTable = table('file', (t) => ({
	id: t.text().notNull().primaryKey().unique(),
	clerkId: t
		.text()
		.notNull()
		.references(() => userTable.clerkId, {
			onUpdate: 'cascade',
			onDelete: 'cascade'
		}),
	docId: t.text().references(() => docTable.id, {
		onUpdate: 'cascade',
		onDelete: 'cascade'
	}),
	type: t.text({
		enum: [
			'PENDING',
			'USER_SUBMITTED',
			'AI_GENERATED_VISUAL',
			'AI_GENERATED_AUDIO',
			'AI_GENERATED_ANALYTICAL',
			'AI_GENERATED_STORY'
		]
	}).default('PENDING'),
	mimeType: t.text().notNull(),
	fileName: t.text(), //optional
	...createdAtUpdatedAt()
}));
export type DBFile = typeof fileTable.$inferSelect;

// ========================= Relations =================================
export const userRelations = relations(userTable, ({ many }) => ({
	profiles: many(profileTable),
	docs: many(docTable)
}));

export const profileRelations = relations(profileTable, ({ many }) => ({
	docs: many(docTable),
	files: many(fileTable)
}));
